### ISSUE TITLE
Cannot execute tests from WSL terminal on Windows 10 

### ISSUE THREAD

**Issue by karlisup** [mondeja/pytest-blender#72]
Hi,
Running 
`pytest --blender-executable "/mnt/c/Program Files/Blender Foundation/Blender 3.0/blender.exe" tests`
returns an error message: 
```
Blender 3.0.1 (hash dc2d18018171 built 2022-01-26 01:46:57)
Read prefs: C:\Users\karli\AppData\Roaming\Blender Foundation\Blender\3.0\config\userpref.blend
OSError: Python file "C:\Users\karli\IdeaProjects\rig\physical-starlight-atmosphere\/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/pytest_blender/run_pytest.py" could not be opened: No such file or directory
```
Which I assume is related to the fact that I am not using the default Windows command prompt, but Windows Subsystem for Linux.

I had a similar issue when executing
`pytest-blender --blender-executable "/mnt/c/Program Files/Blender Foundation/Blender 3.0/blender.exe")` which returned
`C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\bin\python.EXE`
which then I convert to 
`/mnt/c/Program Files/Blender Foundation/Blender 3.0/3.0/python/bin/python.exe`
so I can use it in WSL.

**Comment by mondeja** [comment]
Ok, so what would be the expected path for the `C:\Users\karli\IdeaProjects\rig\physical-starlight-atmosphere\/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/pytest_blender/run_pytest.py` monstruosity?

Note that `run_pytest.py` path is just compounded joining the full path to the same directory as *pytest-blender/* in *site-packages/*, the expected location. In the case of the `pytest-blender` invocation, it just runs `blender -b --python-expr "import sys;print(sys.executable)"`, so in both cases pytest-blender does not take control over that because is happening at OS or Blender's Python interpreter compilation level.

I suspect that the problem is that you are in a Windows system according to Python and in a Linux system according to the subsystem, which is the file path resolver and expects `/` paths separators. Anyways I'm not sure, in Windows we are in a dirty territory. I don't know if Windows encourages users to run files with mixed path separators at all, IHMO feels like a bug in Python or WSL itself.

Personally I would recommend to make a partition of your hard disk and configure a dual boot system with Linux and Windows to avoid this kind of Frankesteins.

**Comment by karlisup** [comment]
I agree it is indeed a monstrosity :). I imagine that my colleagues may not use WSL and it is not as important to run tests from WSL currently. I'll migrate to the cmd prompt and see how it goes. For now, I'll just close this ticket.
